parameters:
  database_driver: pdo_mysql
  database_host: 127.0.0.1
  database_port: null
<<<<<<< HEAD
  database_name: depot
=======
  database_name: depotvente
>>>>>>> 5acf536b1a0797655d90bf4af7a88e47fe665bad
  database_user: root
  database_password: password
  mailer_transport: smtp
  mailer_host: 127.0.0.1
  mailer_user: null
  mailer_password: null
  locale: en
  secret: 9525b2d298d66f383bc1615cffa73c8a
  database_path: null
