<?php

namespace DepotVente\BourseBundle\Entity;

use Doctrine\ORM\EntityRepository;
use DepotVente\BourseBundle\Entity\Bourse;

/**
 * FactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureRepository extends EntityRepository
{

	public function getLast(){
		 $query = $this->createQueryBuilder('f')
		 ->setMaxResults(1)
		 ->orderBy('f.id', 'DESC');

         $r = $query->getQuery()->getOneOrNullResult();
         return ($r != null )? $r->getId() +1 : 1 ;
    }

    public function getFacturesFromBourse($b){
    	$query = $this->createQueryBuilder('f')
        ->where('f.bourse = :bourse')
        ->setParameter('bourse',$b);

	    return $query->getQuery()->getArrayResult();
	}
}
