<?php

namespace DepotVente\BourseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function getTotalArticleVendu(){
		$this->createQueryBuilder
		->select('sum(a.price)')
        ->where('id', '1 ')
        ->getQuery()->getSingleScalarResult();
	}
}
