bourse_homepage:
    pattern:  /
    defaults: { _controller: BourseBundle:Home:index }

bourse_newBourse:
    pattern:  /newBourse
    defaults: { _controller: BourseBundle:Home:createBourse }

bourse_BourseTest:
    pattern:  /bourseTest
    defaults: { _controller: BourseBundle:Home:bourseTest }

bourse_depotpage:
    pattern:  /depot
    defaults: { _controller: BourseBundle:Depot:index }

bourse_boursepage:
    pattern: /bourse
    defaults: { _controller: BourseBundle:Bourse:index }

bourse_article_get:
    pattern: /article
    defaults: { _controller: BourseBundle:Bourse:showArticleGet }

bourse_article:
    pattern: /article/{nro}
    defaults: { _controller: BourseBundle:Bourse:showArticle , nro : 0 }
    requirements :
        nro : "[a-zA-Z0-9]+"

bourse_all_article:
    pattern: /article/tous-les-article/{display}
    defaults: { _controller: BourseBundle:Bourse:showAllArticle , display : liste }
    requirements :
        display : "liste|tableau"

bourse_article_selection:
    pattern: /article/recherche-critere/{display}
    defaults: { _controller: BourseBundle:Bourse:showListArticle, display : liste }
    requirements :
        display : "liste|tableau"

bourse_listenUser:
    pattern: /depot/listenUser
    defaults: { _controller: BourseBundle:Depot:listenUser }

bourse_quitUser:
    pattern: /depot/quitUser
    defaults: { _controller: BourseBundle:Depot:quitUser }

bourse_addArticle:
    pattern: /depot/addArticle
    defaults: { _controller: BourseBundle:Depot:addArticle }

bourse_deleteArticleDepot:
    pattern: /depot/delete-Article-depot/{nro}
    defaults: { _controller: BourseBundle:Depot:deleteArticle }

bourse_saveDepot:
    pattern: /depot/save-depot
    defaults: { _controller: BourseBundle:Depot:saveDepot }

bourse_addArticleFacture:
    pattern: /bourse/add-art-facture
    defaults: { _controller: BourseBundle:Bourse:addArticle }

bourse_removeFacture:
    pattern: /bourse/remove-facture
    defaults: { _controller: BourseBundle:Bourse:removeFacture }

bourse_deleteArticleFacture:
    pattern: /bourse/delete-Article-facture/{id}
    defaults: { _controller: BourseBundle:Bourse:deleteArticle }

bourse_saveFacture:
    pattern: /bourse/saveFacture
    defaults: { _controller: BourseBundle:Bourse:saveFacture }

bourse_deposant:
    pattern: /ficheDeposant/{id}
    defaults: { _controller: BourseBundle:Gestion:ficheDeposant }

bourse_modifArticle:
    pattern: /modif-article/{nro}
    defaults: { _controller: BourseBundle:Gestion:modifArticle }

bourse_deleteArticle:
    pattern: /delete-article/{nro}
    defaults: { _controller: BourseBundle:Gestion:deleteArticle }

bourse_tableauDeBord:
    pattern: /tableau-de-bord
    defaults: { _controller: BourseBundle:Gestion:tableauDeBord }

bourse_closeBourse:
    pattern: /closeBourse
    defaults: { _controller: BourseBundle:Gestion:closeBourse }

bourse_all_deposant:
    pattern: /list-deposant/{display}
    defaults: { _controller: BourseBundle:Depot:showAllDeposant , display : liste}
    requirements :
        display : "liste|tableau"
