bourse_homepage:
    pattern:  /
    defaults: { _controller: BourseBundle:Home:index }

bourse_depotpage:
    pattern:  /depot
    defaults: { _controller: BourseBundle:Article:index }

bourse_boursepage:
    pattern: /bourse
    defaults: { _controller: BourseBundle:Bourse:index }
